### ISSUE TITLE
只显示第一界面，不显示内容

### ISSUE THREAD

**Issue by sdhz151** [changbin1997/Facile#1]
![16200336317620](https://user-images.githubusercontent.com/17267950/166081056-87a2fcdf-6688-4767-b749-98cd8897d5da.png)
点击进入还是到这个界面

**Comment by sdhz151** [comment]
点击阅读全文还是在这个页面，浏览器也刷新了

**Comment by changbin1997** [comment]
切换其他主题试试，看能不能正常显示

**Comment by sdhz151** [comment]
![Screenshot_20220501_095058](https://user-images.githubusercontent.com/17267950/166128920-3f4a1bed-ef99-44d7-9849-88df6fe76eb4.jpg)
默认风格这个主题无法进入内容界面，选择wordpress风格正常使用，谢谢！
