### ISSUE TITLE
图片懒加载功能打开后懒加载似乎没有生效？

### ISSUE THREAD

**Issue by hellodk34** [changbin1997/Facile#12]
![image](https://github.com/user-attachments/assets/de837911-de72-41ab-8896-262139ad3774)

最近写了一篇文章包含很多图片，朋友反馈图片加载体验比较差才意识到。翻了一下 F12 的源代码，img 标签只有 src 和 alt 两个属性，并没有 data-src 属性，请问这是为什么？

![image](https://github.com/user-attachments/assets/9c1ee460-6682-409d-9cd5-4ccddd921516)

**Comment by hellodk34** [comment]
借 GPT4 的帮助，似乎已经修改生效了。

一、

`usr/themes/Facile/compoments/header.php` 适当位置添加 `<script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.2/lazysizes.min.js" async></script>
`

![image](https://github.com/user-attachments/assets/2ae58316-5eb7-4897-8eae-49f51f6e1090)

二、

`functions.php` replaceImgSrc 函数修改，改成如下

```
// 把图片的 src 替换为 data-src，用于图片懒加载
//function replaceImgSrc($content) {
//    $pattern = '/<img(.*?)src(.*?)=(.*?)"(.*?)">/i';
//    $replacement = '<img$1data-src$3="$4"$5 class="load-img">';
//    return preg_replace($pattern, $replacement, $content);
// }
// 上面注释了的是 Facile 2.1.12/2.2 版本当中的代码

function replaceImgSrc($content) {
    $pattern = '/<img(.*?)src=["\'](.*?)["\']/i';
    $replacement = '<img$1data-src="$2" class="load-img"';
    return preg_replace($pattern, $replacement, $content);
}
```

最后查看文章我发现 img 标签已经有 data-src 属性了（确保主题设置中的图片懒加载功能已打开）

![image](https://github.com/user-attachments/assets/5cc61da3-f88a-40b5-bb97-cbb212d4bffc)

麻烦佬抽空看看……

**Comment by changbin1997** [comment]
我测试了一下，只需要开启图片懒加载 `img` 就会包含 `data-src` 。

![浏览器开发者工具截图](https://github.com/user-attachments/assets/f9a06baa-3955-4b98-91ad-8392c16a1dee)

**Comment by hellodk34** [comment]
那有可能是我的什么插件导致的失效…… 估计是 replaceImgSrc 方法里正则表达式的问题。不过我这边也解决了，感谢回复，本issue 我就关了。
